import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiFirebase,
  SiTypescript,
  SiGooglegemini,
  SiPostgresql,
  SiReact,
  SiMongodb,
  SiWebrtc,
  SiExpress,
  SiPython,
  SiNodedotjs,
  SiApollographql,
  SiRedux,
  SiAwselasticloadbalancing,
  SiDocker,
  SiFlask,
  SiSocialblade,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaFootball,
} from "react-icons/fa6";
import { BiFoodMenu, BiLaptop } from "react-icons/bi";
import { TbTrekking } from "react-icons/tb";
import { MdTravelExplore } from "react-icons/md";
import { FcCandleSticks } from "react-icons/fc";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  sports: FaFootball,
  food: BiFoodMenu,
  treking: TbTrekking,
  travel: MdTravelExplore,
  code: BiLaptop,
  gallery: PiImageDuotone,
  stocks: FcCandleSticks,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  firebase: SiFirebase,
  typescript: SiTypescript,
  genkit: SiGooglegemini,
  postgresql: SiPostgresql,
  reactjs: SiReact,
  mongodb: SiMongodb,
  webrtc: SiWebrtc,
  reactnative: SiReact,
  expressjs: SiExpress,
  python: SiPython,
  nodejs: SiNodedotjs,
  apollo: SiApollographql,
  redux: SiRedux,
  aws: SiAwselasticloadbalancing,
  docker: SiDocker,
  flask: SiFlask,
  git: FaGithub,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
